//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Windowsproject.Properties {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Windowsproject.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 BookId,Title,Author,Category,Status,Borrower,DueDate,Rating,AddedDate,Description,RatingCount,RatingSum
        ///B0001,解憂柑仔店,藤野圭吾,文學小說,在館中,,,3,2026-06-01,一間神奇的雜貨店，煩惱投進信箱便能得到回覆。三個少年的奇遇，串起了跨越時空的人情與救贖。,1,3
        ///B0002,從零學C尖,王小銘,資訊科技,在館中,,,4,2026-06-10,從零開始學習 C# 程式語言，涵蓋基礎語法、物件導向概念，到實際應用開發，適合完全沒有程式基礎的初學者。,3,11
        ///B0003,有錢爸爸沒錢爸爸,羅伯・清崎,商業理財,在館中,,,4,2026-05-20,用兩位父親的理財觀念對比，教導讀者如何建立財務自由的思維，讓錢為你工作而不是你為錢工作。,3,11
        ///B0004,少即是設計,原硏哉,藝術設計,在館中,,,4,2026-06-15,日本設計大師探討空的美學，以極簡主義重新定義設計的本質，是平面與產品設計的經典之作。,2,7
        ///B0005,春樹物語選集,村上晴樹,文學小說,在館中,,,4,20 [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string Books {
            get {
                return ResourceManager.GetString("Books", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Username,Password
        ///Daniel,111
        ///HHHH,5555
        ///123,123
        ///ABC,999
        ///HHHHHHHH,123456
        ///GAAAAA,123456
        ///HHHHHHH,CCC
        /// 的當地語系化字串。
        /// </summary>
        internal static string users {
            get {
                return ResourceManager.GetString("users", resourceCulture);
            }
        }
    }
}
